import { Food } from '../src/types';

export const STARTER_FOODS: Food[] = [
  // ==========================================
  // 1. INDIAN MEALS (35 items)
  // ==========================================
  { id: 'im-1', name: 'Rajma Chawal (Kidney Beans & Rice)', category: 'Indian Meals', servingUnit: '1 plate (350g)', servingGrams: 350, calories: 420, protein: 16.5, carbs: 74, fat: 5.5, fiber: 9.2, verified: true },
  { id: 'im-2', name: 'Chole Masala (Chickpea Curry)', category: 'Indian Meals', servingUnit: '1 bowl (200g)', servingGrams: 200, calories: 260, protein: 12.0, carbs: 36, fat: 6.5, fiber: 8.5, verified: true },
  { id: 'im-3', name: 'Dal Makhani (Black Lentil with Cream)', category: 'Indian Meals', servingUnit: '1 bowl (200g)', servingGrams: 200, calories: 310, protein: 11.5, carbs: 28, fat: 16.0, fiber: 7.0, verified: true },
  { id: 'im-4', name: 'Yellow Moong Dal Tadka', category: 'Indian Meals', servingUnit: '1 bowl (180g)', servingGrams: 180, calories: 160, protein: 9.5, carbs: 23, fat: 3.5, fiber: 4.5, verified: true },
  { id: 'im-5', name: 'Toor Dal / Arhar Dal Fry', category: 'Indian Meals', servingUnit: '1 bowl (180g)', servingGrams: 180, calories: 175, protein: 9.8, carbs: 24, fat: 4.2, fiber: 4.8, verified: true },
  { id: 'im-6', name: 'Paneer Butter Masala', category: 'Indian Meals', servingUnit: '1 bowl (220g)', servingGrams: 220, calories: 380, protein: 15.0, carbs: 14, fat: 28.0, fiber: 2.5, verified: true },
  { id: 'im-7', name: 'Palak Paneer (Spinach & Cottage Cheese)', category: 'Indian Meals', servingUnit: '1 bowl (220g)', servingGrams: 220, calories: 270, protein: 16.5, carbs: 9, fat: 18.5, fiber: 4.2, verified: true },
  { id: 'im-8', name: 'Kadai Paneer', category: 'Indian Meals', servingUnit: '1 bowl (200g)', servingGrams: 200, calories: 310, protein: 16.0, carbs: 12, fat: 22.0, fiber: 3.0, verified: true },
  { id: 'im-9', name: 'Matar Paneer', category: 'Indian Meals', servingUnit: '1 bowl (200g)', servingGrams: 200, calories: 280, protein: 14.5, carbs: 18, fat: 16.5, fiber: 4.0, verified: true },
  { id: 'im-10', name: 'Shahi Paneer (Rich Cashew Gravy)', category: 'Indian Meals', servingUnit: '1 bowl (220g)', servingGrams: 220, calories: 395, protein: 14.0, carbs: 16, fat: 30.0, fiber: 2.0, verified: true },
  { id: 'im-11', name: 'Paneer Bhurji (Scrambled Cottage Cheese)', category: 'Indian Meals', servingUnit: '1 plate (150g)', servingGrams: 150, calories: 310, protein: 19.5, carbs: 6, fat: 23.0, fiber: 1.5, verified: true },
  { id: 'im-12', name: 'Soya Chunks Curry (High Protein)', category: 'Indian Meals', servingUnit: '1 bowl (200g)', servingGrams: 200, calories: 230, protein: 24.0, carbs: 18, fat: 4.5, fiber: 7.5, verified: true },
  { id: 'im-13', name: 'Chicken Curry (Home-Style Tariwala)', category: 'Indian Meals', servingUnit: '1 bowl (220g)', servingGrams: 220, calories: 290, protein: 32.0, carbs: 6, fat: 14.5, fiber: 1.8, verified: true },
  { id: 'im-14', name: 'Butter Chicken (Murgh Makhani)', category: 'Indian Meals', servingUnit: '1 bowl (220g)', servingGrams: 220, calories: 420, protein: 30.0, carbs: 12, fat: 28.0, fiber: 1.5, verified: true },
  { id: 'im-15', name: 'Kadai Chicken', category: 'Indian Meals', servingUnit: '1 bowl (220g)', servingGrams: 220, calories: 330, protein: 34.0, carbs: 8, fat: 17.5, fiber: 2.0, verified: true },
  { id: 'im-16', name: 'Egg Curry (2 Boiled Eggs in Onion-Tomato Gravy)', category: 'Indian Meals', servingUnit: '1 bowl (220g)', servingGrams: 220, calories: 260, protein: 16.0, carbs: 10, fat: 16.5, fiber: 2.2, verified: true },
  { id: 'im-17', name: 'Fish Curry (Rohu / Katla Mustard Gravy)', category: 'Indian Meals', servingUnit: '1 bowl (220g)', servingGrams: 220, calories: 240, protein: 26.0, carbs: 5, fat: 12.0, fiber: 1.2, verified: true },
  { id: 'im-18', name: 'Mutton Curry / Rogan Josh', category: 'Indian Meals', servingUnit: '1 bowl (220g)', servingGrams: 220, calories: 410, protein: 28.0, carbs: 7, fat: 30.0, fiber: 1.5, verified: true },
  { id: 'im-19', name: 'Aloo Gobi Masala', category: 'Indian Meals', servingUnit: '1 bowl (180g)', servingGrams: 180, calories: 170, protein: 4.2, carbs: 24, fat: 6.5, fiber: 4.5, verified: true },
  { id: 'im-20', name: 'Bhindi Masala (Okra Stir-Fry)', category: 'Indian Meals', servingUnit: '1 bowl (160g)', servingGrams: 160, calories: 140, protein: 3.5, carbs: 16, fat: 6.8, fiber: 4.8, verified: true },
  { id: 'im-21', name: 'Baingan Bharta (Roasted Eggplant Mash)', category: 'Indian Meals', servingUnit: '1 bowl (180g)', servingGrams: 180, calories: 155, protein: 3.0, carbs: 18, fat: 7.5, fiber: 5.5, verified: true },
  { id: 'im-22', name: 'Kadhi Pakora (Gram Flour & Yogurt Stew)', category: 'Indian Meals', servingUnit: '1 bowl (220g)', servingGrams: 220, calories: 270, protein: 8.5, carbs: 26, fat: 14.5, fiber: 2.8, verified: true },
  { id: 'im-23', name: 'Khichdi (Moong Dal & Rice with Ghee)', category: 'Indian Meals', servingUnit: '1 large bowl (300g)', servingGrams: 300, calories: 340, protein: 12.0, carbs: 58, fat: 6.5, fiber: 5.0, verified: true },
  { id: 'im-24', name: 'Sambhar (South Indian Lentil & Vegetable Stew)', category: 'Indian Meals', servingUnit: '1 bowl (220g)', servingGrams: 220, calories: 135, protein: 6.5, carbs: 21, fat: 2.8, fiber: 4.5, verified: true },
  { id: 'im-25', name: 'Chana Masala (Punjabi Style)', category: 'Indian Meals', servingUnit: '1 bowl (200g)', servingGrams: 200, calories: 250, protein: 11.5, carbs: 35, fat: 6.5, fiber: 8.0, verified: true },
  { id: 'im-26', name: 'Mix Veg Curry (Carrot, Peas, Beans, Paneer)', category: 'Indian Meals', servingUnit: '1 bowl (200g)', servingGrams: 200, calories: 195, protein: 6.5, carbs: 20, fat: 9.5, fiber: 4.8, verified: true },
  { id: 'im-27', name: 'Dum Aloo (Spiced Baby Potatoes)', category: 'Indian Meals', servingUnit: '1 bowl (200g)', servingGrams: 200, calories: 245, protein: 4.0, carbs: 34, fat: 10.5, fiber: 3.8, verified: true },
  { id: 'im-28', name: 'Sarson Ka Saag (Mustard Greens with Makki Roti)', category: 'Indian Meals', servingUnit: '1 bowl (200g)', servingGrams: 200, calories: 190, protein: 6.0, carbs: 16, fat: 11.0, fiber: 6.2, verified: true },
  { id: 'im-29', name: 'Methi Malai Matar', category: 'Indian Meals', servingUnit: '1 bowl (200g)', servingGrams: 200, calories: 295, protein: 7.5, carbs: 22, fat: 19.5, fiber: 4.5, verified: true },
  { id: 'im-30', name: 'Lauki Ki Sabzi (Bottle Gourd Light Curry)', category: 'Indian Meals', servingUnit: '1 bowl (180g)', servingGrams: 180, calories: 95, protein: 2.2, carbs: 12, fat: 4.0, fiber: 3.2, verified: true },
  { id: 'im-31', name: 'Gatte Ki Sabzi (Gram Flour Dumplings)', category: 'Indian Meals', servingUnit: '1 bowl (200g)', servingGrams: 200, calories: 280, protein: 10.5, carbs: 25, fat: 15.0, fiber: 4.0, verified: true },
  { id: 'im-32', name: 'Pav Bhaji (Mashed Spiced Veggies - No Pav)', category: 'Indian Meals', servingUnit: '1 bowl (200g)', servingGrams: 200, calories: 210, protein: 5.2, carbs: 26, fat: 9.5, fiber: 5.5, verified: true },
  { id: 'im-33', name: 'Kala Chana Gravy (Black Chickpea Curry)', category: 'Indian Meals', servingUnit: '1 bowl (200g)', servingGrams: 200, calories: 240, protein: 13.0, carbs: 34, fat: 5.0, fiber: 9.5, verified: true },
  { id: 'im-34', name: 'Malai Kofta (Cottage Cheese & Potato Dumplings in Cream)', category: 'Indian Meals', servingUnit: '1 bowl (220g)', servingGrams: 220, calories: 430, protein: 10.0, carbs: 30, fat: 30.5, fiber: 3.0, verified: true },
  { id: 'im-35', name: 'Lobia Masala (Black Eyed Peas Curry)', category: 'Indian Meals', servingUnit: '1 bowl (200g)', servingGrams: 200, calories: 225, protein: 12.5, carbs: 32, fat: 4.5, fiber: 7.8, verified: true },

  // ==========================================
  // 2. INDIAN SNACKS (30 items)
  // ==========================================
  { id: 'is-1', name: 'Poha (Flattened Rice with Peanuts & Veggies)', category: 'Indian Snacks', servingUnit: '1 plate (160g)', servingGrams: 160, calories: 245, protein: 5.2, carbs: 44, fat: 5.5, fiber: 3.5, verified: true },
  { id: 'is-2', name: 'Upma (Semolina with Mustard & Curry Leaves)', category: 'Indian Snacks', servingUnit: '1 plate (160g)', servingGrams: 160, calories: 225, protein: 5.5, carbs: 38, fat: 5.0, fiber: 2.8, verified: true },
  { id: 'is-3', name: 'Idli (Steamed Rice & Urad Cake)', category: 'Indian Snacks', servingUnit: '2 pieces (100g)', servingGrams: 100, calories: 140, protein: 4.5, carbs: 28, fat: 0.6, fiber: 2.0, verified: true },
  { id: 'is-4', name: 'Plain Dosa', category: 'Indian Snacks', servingUnit: '1 medium (90g)', servingGrams: 90, calories: 168, protein: 3.9, carbs: 29, fat: 3.8, fiber: 1.8, verified: true },
  { id: 'is-5', name: 'Masala Dosa with Potato Filling', category: 'Indian Snacks', servingUnit: '1 piece (180g)', servingGrams: 180, calories: 320, protein: 6.8, carbs: 48, fat: 11.5, fiber: 3.6, verified: true },
  { id: 'is-6', name: 'Medu Vada (Fried Lentil Donut)', category: 'Indian Snacks', servingUnit: '2 pieces (100g)', servingGrams: 100, calories: 260, protein: 7.5, carbs: 25, fat: 14.5, fiber: 3.2, verified: true },
  { id: 'is-7', name: 'Uttapam (Onion & Tomato Topped)', category: 'Indian Snacks', servingUnit: '1 medium (150g)', servingGrams: 150, calories: 230, protein: 5.8, carbs: 39, fat: 5.2, fiber: 3.0, verified: true },
  { id: 'is-8', name: 'Dhokla (Khaman Steamed Gram Flour)', category: 'Indian Snacks', servingUnit: '4 pieces (120g)', servingGrams: 120, calories: 180, protein: 7.2, carbs: 28, fat: 4.2, fiber: 3.5, verified: true },
  { id: 'is-9', name: 'Khandvi (Steamed Spiced Gram Rolls)', category: 'Indian Snacks', servingUnit: '4 pieces (100g)', servingGrams: 100, calories: 150, protein: 6.0, carbs: 18, fat: 6.0, fiber: 2.5, verified: true },
  { id: 'is-10', name: 'Paneer Tikka (Grilled Tandoori Cubes)', category: 'Indian Snacks', servingUnit: '6 pieces (150g)', servingGrams: 150, calories: 290, protein: 21.0, carbs: 7, fat: 19.5, fiber: 1.5, verified: true },
  { id: 'is-11', name: 'Chicken Tikka (Boneless Grilled Tandoori)', category: 'Indian Snacks', servingUnit: '6 pieces (160g)', servingGrams: 160, calories: 240, protein: 36.0, carbs: 3, fat: 8.5, fiber: 0.8, verified: true },
  { id: 'is-12', name: 'Tandoori Chicken (Quarter Leg & Thigh)', category: 'Indian Snacks', servingUnit: '1 piece (180g)', servingGrams: 180, calories: 275, protein: 38.0, carbs: 3, fat: 11.5, fiber: 0.5, verified: true },
  { id: 'is-13', name: 'Soya Chaap (Tandoori Grilled)', category: 'Indian Snacks', servingUnit: '1 plate (150g)', servingGrams: 150, calories: 260, protein: 22.0, carbs: 18, fat: 9.8, fiber: 4.5, verified: true },
  { id: 'is-14', name: 'Hara Bhara Kabab (Spinach & Peas Patty)', category: 'Indian Snacks', servingUnit: '3 pieces (120g)', servingGrams: 120, calories: 210, protein: 6.5, carbs: 24, fat: 10.0, fiber: 4.2, verified: true },
  { id: 'is-15', name: 'Sprouted Moong Chaat (With Onion & Lemon)', category: 'Indian Snacks', servingUnit: '1 bowl (150g)', servingGrams: 150, calories: 160, protein: 11.2, carbs: 26, fat: 1.2, fiber: 6.5, verified: true },
  { id: 'is-16', name: 'Roasted Makhana (Fox Nuts in Ghee)', category: 'Indian Snacks', servingUnit: '1 bowl (40g)', servingGrams: 40, calories: 165, protein: 3.8, carbs: 28, fat: 4.2, fiber: 3.0, verified: true },
  { id: 'is-17', name: 'Roasted Kala Chana (Black Chickpeas with Skin)', category: 'Indian Snacks', servingUnit: '1 handful (50g)', servingGrams: 50, calories: 185, protein: 10.5, carbs: 28, fat: 2.8, fiber: 8.5, verified: true },
  { id: 'is-18', name: 'Samosa (Fried Potato Stuffed)', category: 'Indian Snacks', servingUnit: '1 piece (90g)', servingGrams: 90, calories: 260, protein: 4.0, carbs: 32, fat: 13.5, fiber: 2.2, verified: true },
  { id: 'is-19', name: 'Pani Puri / Golgappe (6 Puris with Spiced Water & Potato)', category: 'Indian Snacks', servingUnit: '6 pieces (150g)', servingGrams: 150, calories: 190, protein: 3.5, carbs: 36, fat: 3.8, fiber: 2.0, verified: true },
  { id: 'is-20', name: 'Bhel Puri (Puffed Rice with Sev & Chutneys)', category: 'Indian Snacks', servingUnit: '1 plate (150g)', servingGrams: 150, calories: 280, protein: 5.5, carbs: 48, fat: 8.0, fiber: 3.5, verified: true },
  { id: 'is-21', name: 'Sev Puri', category: 'Indian Snacks', servingUnit: '1 plate (150g)', servingGrams: 150, calories: 310, protein: 5.0, carbs: 42, fat: 14.0, fiber: 2.8, verified: true },
  { id: 'is-22', name: 'Dahi Bhalla / Dahi Vada (with Sweet Curd & Tamarind)', category: 'Indian Snacks', servingUnit: '2 pieces (180g)', servingGrams: 180, calories: 290, protein: 8.5, carbs: 38, fat: 11.5, fiber: 2.5, verified: true },
  { id: 'is-23', name: 'Aloo Tikki (Pan-Fried Potato Patty)', category: 'Indian Snacks', servingUnit: '2 pieces (140g)', servingGrams: 140, calories: 270, protein: 4.2, carbs: 34, fat: 13.0, fiber: 3.0, verified: true },
  { id: 'is-24', name: 'Besan Chilla (Savory Gram Flour Pancake with Veggies)', category: 'Indian Snacks', servingUnit: '2 chillas (140g)', servingGrams: 140, calories: 210, protein: 11.0, carbs: 26, fat: 6.5, fiber: 5.0, verified: true },
  { id: 'is-25', name: 'Moong Dal Chilla (Yellow Lentil Crepe)', category: 'Indian Snacks', servingUnit: '2 chillas (140g)', servingGrams: 140, calories: 220, protein: 14.0, carbs: 28, fat: 5.5, fiber: 6.0, verified: true },
  { id: 'is-26', name: 'Methi Thepla (Spiced Fenugreek Flatbread)', category: 'Indian Snacks', servingUnit: '2 pieces (80g)', servingGrams: 80, calories: 230, protein: 6.0, carbs: 32, fat: 8.5, fiber: 4.0, verified: true },
  { id: 'is-27', name: 'Roasted Peanuts with Salt', category: 'Indian Snacks', servingUnit: '1 handful (35g)', servingGrams: 35, calories: 205, protein: 9.0, carbs: 6, fat: 17.5, fiber: 3.0, verified: true },
  { id: 'is-28', name: 'Kachori (Pyaz / Dal Fried)', category: 'Indian Snacks', servingUnit: '1 piece (80g)', servingGrams: 80, calories: 285, protein: 4.8, carbs: 30, fat: 16.5, fiber: 2.0, verified: true },
  { id: 'is-29', name: 'Murukku / Chakli', category: 'Indian Snacks', servingUnit: '3 pieces (40g)', servingGrams: 40, calories: 215, protein: 3.0, carbs: 24, fat: 12.0, fiber: 1.5, verified: true },
  { id: 'is-30', name: 'Corn Chaat (Boiled Sweetcorn with Lime & Chaat Masala)', category: 'Indian Snacks', servingUnit: '1 cup (150g)', servingGrams: 150, calories: 140, protein: 4.8, carbs: 29, fat: 1.8, fiber: 3.5, verified: true },

  // ==========================================
  // 3. FRUITS (25 items)
  // ==========================================
  { id: 'fr-1', name: 'Banana (Ripe)', category: 'Fruits', servingUnit: '1 medium (120g)', servingGrams: 120, calories: 105, protein: 1.3, carbs: 27.0, fat: 0.3, fiber: 3.1, verified: true },
  { id: 'fr-2', name: 'Apple (Fresh with Skin)', category: 'Fruits', servingUnit: '1 medium (160g)', servingGrams: 160, calories: 85, protein: 0.5, carbs: 22.0, fat: 0.3, fiber: 4.4, verified: true },
  { id: 'fr-3', name: 'Papaya (Fresh Cubes)', category: 'Fruits', servingUnit: '1 bowl (160g)', servingGrams: 160, calories: 68, protein: 0.8, carbs: 17.0, fat: 0.4, fiber: 2.7, verified: true },
  { id: 'fr-4', name: 'Mango (Alphonso / Langra Slices)', category: 'Fruits', servingUnit: '1 cup (165g)', servingGrams: 165, calories: 100, protein: 1.4, carbs: 25.0, fat: 0.6, fiber: 2.6, verified: true },
  { id: 'fr-5', name: 'Guava (Amrood - High Fiber)', category: 'Fruits', servingUnit: '1 medium (120g)', servingGrams: 120, calories: 80, protein: 3.0, carbs: 17.0, fat: 1.1, fiber: 6.5, verified: true },
  { id: 'fr-6', name: 'Watermelon (Fresh Diced)', category: 'Fruits', servingUnit: '1 large bowl (250g)', servingGrams: 250, calories: 75, protein: 1.5, carbs: 19.0, fat: 0.4, fiber: 1.0, verified: true },
  { id: 'fr-7', name: 'Pomegranate Seeds (Anar)', category: 'Fruits', servingUnit: '1 cup (150g)', servingGrams: 150, calories: 125, protein: 2.5, carbs: 28.0, fat: 1.8, fiber: 6.0, verified: true },
  { id: 'fr-8', name: 'Orange / Santra', category: 'Fruits', servingUnit: '1 fruit (140g)', servingGrams: 140, calories: 65, protein: 1.3, carbs: 15.5, fat: 0.2, fiber: 3.4, verified: true },
  { id: 'fr-9', name: 'Sweet Lime / Mosambi', category: 'Fruits', servingUnit: '1 fruit (130g)', servingGrams: 130, calories: 55, protein: 1.0, carbs: 13.5, fat: 0.2, fiber: 2.8, verified: true },
  { id: 'fr-10', name: 'Green Grapes', category: 'Fruits', servingUnit: '1 cup (150g)', servingGrams: 150, calories: 104, protein: 1.1, carbs: 27.0, fat: 0.2, fiber: 1.4, verified: true },
  { id: 'fr-11', name: 'Black Grapes', category: 'Fruits', servingUnit: '1 cup (150g)', servingGrams: 150, calories: 106, protein: 1.1, carbs: 27.5, fat: 0.3, fiber: 1.5, verified: true },
  { id: 'fr-12', name: 'Pineapple Chunks', category: 'Fruits', servingUnit: '1 cup (165g)', servingGrams: 165, calories: 82, protein: 0.9, carbs: 21.5, fat: 0.2, fiber: 2.3, verified: true },
  { id: 'fr-13', name: 'Kiwi (Green Fresh)', category: 'Fruits', servingUnit: '1 fruit (75g)', servingGrams: 75, calories: 46, protein: 0.9, carbs: 11.0, fat: 0.4, fiber: 2.3, verified: true },
  { id: 'fr-14', name: 'Strawberries (Fresh)', category: 'Fruits', servingUnit: '1 cup (150g)', servingGrams: 150, calories: 48, protein: 1.0, carbs: 11.5, fat: 0.5, fiber: 3.0, verified: true },
  { id: 'fr-15', name: 'Blueberries', category: 'Fruits', servingUnit: '1 cup (145g)', servingGrams: 145, calories: 84, protein: 1.1, carbs: 21.0, fat: 0.5, fiber: 3.6, verified: true },
  { id: 'fr-16', name: 'Chiku / Sapodilla', category: 'Fruits', servingUnit: '1 fruit (100g)', servingGrams: 100, calories: 83, protein: 0.4, carbs: 20.0, fat: 1.1, fiber: 5.3, verified: true },
  { id: 'fr-17', name: 'Custard Apple / Sitaphal', category: 'Fruits', servingUnit: '1 fruit (150g flesh)', servingGrams: 150, calories: 140, protein: 2.5, carbs: 35.0, fat: 0.5, fiber: 4.4, verified: true },
  { id: 'fr-18', name: 'Dragon Fruit (Pitaya)', category: 'Fruits', servingUnit: '1 cup (150g)', servingGrams: 150, calories: 90, protein: 1.8, carbs: 19.0, fat: 0.8, fiber: 4.5, verified: true },
  { id: 'fr-19', name: 'Pear / Nashpati', category: 'Fruits', servingUnit: '1 medium (170g)', servingGrams: 170, calories: 95, protein: 0.6, carbs: 25.0, fat: 0.2, fiber: 5.3, verified: true },
  { id: 'fr-20', name: 'Peach / Aloo Bukhara', category: 'Fruits', servingUnit: '1 fruit (130g)', servingGrams: 130, calories: 50, protein: 1.2, carbs: 12.0, fat: 0.3, fiber: 2.0, verified: true },
  { id: 'fr-21', name: 'Dates / Khajoor (Medjool/Dry)', category: 'Fruits', servingUnit: '3 dates (45g)', servingGrams: 45, calories: 125, protein: 1.1, carbs: 33.0, fat: 0.2, fiber: 3.2, verified: true },
  { id: 'fr-22', name: 'Dried Figs / Anjeer', category: 'Fruits', servingUnit: '3 pieces (30g)', servingGrams: 30, calories: 75, protein: 1.0, carbs: 19.0, fat: 0.3, fiber: 3.0, verified: true },
  { id: 'fr-23', name: 'Raisins / Kishmish', category: 'Fruits', servingUnit: '1 handful (30g)', servingGrams: 30, calories: 90, protein: 0.9, carbs: 23.5, fat: 0.1, fiber: 1.2, verified: true },
  { id: 'fr-24', name: 'Muskmelon / Kharbuja', category: 'Fruits', servingUnit: '1 bowl (180g)', servingGrams: 180, calories: 60, protein: 1.5, carbs: 14.5, fat: 0.3, fiber: 1.6, verified: true },
  { id: 'fr-25', name: 'Avocado (Fresh Ripe)', category: 'Fruits', servingUnit: 'half avocado (100g)', servingGrams: 100, calories: 160, protein: 2.0, carbs: 8.5, fat: 14.7, fiber: 6.7, verified: true },

  // ==========================================
  // 4. VEGETABLES (30 items)
  // ==========================================
  { id: 'vg-1', name: 'Spinach (Palak Raw/Steamed)', category: 'Vegetables', servingUnit: '1 bowl (100g)', servingGrams: 100, calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2, verified: true },
  { id: 'vg-2', name: 'Broccoli (Steamed)', category: 'Vegetables', servingUnit: '1 cup (150g)', servingGrams: 150, calories: 52, protein: 4.2, carbs: 10.0, fat: 0.6, fiber: 3.9, verified: true },
  { id: 'vg-3', name: 'Cauliflower / Phool Gobi (Raw/Boiled)', category: 'Vegetables', servingUnit: '1 cup (100g)', servingGrams: 100, calories: 25, protein: 2.0, carbs: 5.0, fat: 0.3, fiber: 2.0, verified: true },
  { id: 'vg-4', name: 'Cabbage / Patta Gobi (Shredded)', category: 'Vegetables', servingUnit: '1 cup (100g)', servingGrams: 100, calories: 24, protein: 1.3, carbs: 5.8, fat: 0.1, fiber: 2.5, verified: true },
  { id: 'vg-5', name: 'Tomato (Fresh Sliced)', category: 'Vegetables', servingUnit: '1 medium (120g)', servingGrams: 120, calories: 22, protein: 1.1, carbs: 4.7, fat: 0.2, fiber: 1.4, verified: true },
  { id: 'vg-6', name: 'Onion / Pyaz (Chopped)', category: 'Vegetables', servingUnit: '1 medium (100g)', servingGrams: 100, calories: 40, protein: 1.1, carbs: 9.3, fat: 0.1, fiber: 1.7, verified: true },
  { id: 'vg-7', name: 'Cucumber / Kheera (Raw Salad)', category: 'Vegetables', servingUnit: '1 medium (150g)', servingGrams: 150, calories: 24, protein: 1.0, carbs: 5.0, fat: 0.2, fiber: 1.2, verified: true },
  { id: 'vg-8', name: 'Carrot / Gajar (Raw/Boiled)', category: 'Vegetables', servingUnit: '1 medium (100g)', servingGrams: 100, calories: 41, protein: 0.9, carbs: 9.6, fat: 0.2, fiber: 2.8, verified: true },
  { id: 'vg-9', name: 'Beetroot / Chukandar (Boiled/Raw)', category: 'Vegetables', servingUnit: '1 medium (100g)', servingGrams: 100, calories: 44, protein: 1.6, carbs: 10.0, fat: 0.2, fiber: 2.8, verified: true },
  { id: 'vg-10', name: 'Capsicum / Green Bell Pepper', category: 'Vegetables', servingUnit: '1 medium (120g)', servingGrams: 120, calories: 24, protein: 1.0, carbs: 5.5, fat: 0.2, fiber: 2.0, verified: true },
  { id: 'vg-11', name: 'Red / Yellow Bell Pepper', category: 'Vegetables', servingUnit: '1 medium (120g)', servingGrams: 120, calories: 32, protein: 1.2, carbs: 7.0, fat: 0.3, fiber: 2.5, verified: true },
  { id: 'vg-12', name: 'Green French Beans', category: 'Vegetables', servingUnit: '1 cup (100g)', servingGrams: 100, calories: 31, protein: 1.8, carbs: 7.0, fat: 0.2, fiber: 3.4, verified: true },
  { id: 'vg-13', name: 'Green Peas / Matar (Boiled)', category: 'Vegetables', servingUnit: '1 cup (150g)', servingGrams: 150, calories: 125, protein: 8.2, carbs: 22.5, fat: 0.6, fiber: 7.5, verified: true },
  { id: 'vg-14', name: 'Bottle Gourd / Lauki', category: 'Vegetables', servingUnit: '1 cup chopped (120g)', servingGrams: 120, calories: 18, protein: 0.8, carbs: 4.0, fat: 0.1, fiber: 1.5, verified: true },
  { id: 'vg-15', name: 'Bitter Gourd / Karela', category: 'Vegetables', servingUnit: '1 cup (100g)', servingGrams: 100, calories: 20, protein: 1.0, carbs: 4.3, fat: 0.2, fiber: 2.8, verified: true },
  { id: 'vg-16', name: 'Ridge Gourd / Torai', category: 'Vegetables', servingUnit: '1 cup (100g)', servingGrams: 100, calories: 18, protein: 0.9, carbs: 3.8, fat: 0.1, fiber: 1.6, verified: true },
  { id: 'vg-17', name: 'Lady Finger / Bhindi', category: 'Vegetables', servingUnit: '1 cup (100g)', servingGrams: 100, calories: 33, protein: 1.9, carbs: 7.5, fat: 0.2, fiber: 3.2, verified: true },
  { id: 'vg-18', name: 'Button Mushrooms (Fresh)', category: 'Vegetables', servingUnit: '1 cup (100g)', servingGrams: 100, calories: 22, protein: 3.1, carbs: 3.3, fat: 0.3, fiber: 1.0, verified: true },
  { id: 'vg-19', name: 'Boiled Potato (Aloo)', category: 'Vegetables', servingUnit: '1 medium (150g)', servingGrams: 150, calories: 130, protein: 3.0, carbs: 30.0, fat: 0.2, fiber: 2.6, verified: true },
  { id: 'vg-20', name: 'Sweet Potato (Shakarkandi Boiled)', category: 'Vegetables', servingUnit: '1 medium (130g)', servingGrams: 130, calories: 112, protein: 2.0, carbs: 26.0, fat: 0.1, fiber: 3.9, verified: true },
  { id: 'vg-21', name: 'Zucchini / Courgette (Raw/Grilled)', category: 'Vegetables', servingUnit: '1 cup (120g)', servingGrams: 120, calories: 20, protein: 1.5, carbs: 3.8, fat: 0.4, fiber: 1.2, verified: true },
  { id: 'vg-22', name: 'Radish / Mooli (White Raw)', category: 'Vegetables', servingUnit: '1 medium (100g)', servingGrams: 100, calories: 16, protein: 0.7, carbs: 3.4, fat: 0.1, fiber: 1.6, verified: true },
  { id: 'vg-23', name: 'Pumpkin / Kaddu (Boiled/Cooked)', category: 'Vegetables', servingUnit: '1 cup (150g)', servingGrams: 150, calories: 39, protein: 1.5, carbs: 9.0, fat: 0.2, fiber: 1.8, verified: true },
  { id: 'vg-24', name: 'Fenugreek Leaves / Fresh Methi', category: 'Vegetables', servingUnit: '1 cup (80g)', servingGrams: 80, calories: 35, protein: 3.5, carbs: 5.0, fat: 0.7, fiber: 3.0, verified: true },
  { id: 'vg-25', name: 'Mustard Greens / Sarson Leaves', category: 'Vegetables', servingUnit: '1 cup (100g)', servingGrams: 100, calories: 27, protein: 2.7, carbs: 4.7, fat: 0.4, fiber: 3.2, verified: true },
  { id: 'vg-26', name: 'Garlic Cloves (Raw Lahsun)', category: 'Vegetables', servingUnit: '4 cloves (12g)', servingGrams: 12, calories: 18, protein: 0.8, carbs: 4.0, fat: 0.1, fiber: 0.3, verified: true },
  { id: 'vg-27', name: 'Ginger Root (Adrak Raw)', category: 'Vegetables', servingUnit: '1 tbsp minced (15g)', servingGrams: 15, calories: 12, protein: 0.3, carbs: 2.7, fat: 0.1, fiber: 0.3, verified: true },
  { id: 'vg-28', name: 'Asparagus (Steamed/Grilled)', category: 'Vegetables', servingUnit: '1 cup (130g)', servingGrams: 130, calories: 27, protein: 3.0, carbs: 5.2, fat: 0.2, fiber: 2.8, verified: true },
  { id: 'vg-29', name: 'Lettuce / Salad Greens', category: 'Vegetables', servingUnit: '2 cups (100g)', servingGrams: 100, calories: 15, protein: 1.4, carbs: 2.8, fat: 0.2, fiber: 1.3, verified: true },
  { id: 'vg-30', name: 'Eggplant / Brinjal (Raw/Chopped)', category: 'Vegetables', servingUnit: '1 cup (100g)', servingGrams: 100, calories: 25, protein: 1.0, carbs: 6.0, fat: 0.2, fiber: 3.0, verified: true },

  // ==========================================
  // 5. DAIRY (25 items)
  // ==========================================
  { id: 'dr-1', name: 'Cow Milk (Toned 3% Fat)', category: 'Dairy', servingUnit: '1 glass (250ml)', servingGrams: 250, calories: 145, protein: 8.0, carbs: 12.0, fat: 7.5, fiber: 0, verified: true },
  { id: 'dr-2', name: 'Cow Milk (Double Toned / Skimmed 1.5%)', category: 'Dairy', servingUnit: '1 glass (250ml)', servingGrams: 250, calories: 110, protein: 8.2, carbs: 12.5, fat: 3.8, fiber: 0, verified: true },
  { id: 'dr-3', name: 'Buffalo Milk (Full Fat 6%)', category: 'Dairy', servingUnit: '1 glass (250ml)', servingGrams: 250, calories: 240, protein: 9.5, carbs: 13.0, fat: 16.0, fiber: 0, verified: true },
  { id: 'dr-4', name: 'Fresh Paneer (Raw Cottage Cheese)', category: 'Dairy', servingUnit: '100g', servingGrams: 100, calories: 265, protein: 18.3, carbs: 3.4, fat: 20.8, fiber: 0, verified: true },
  { id: 'dr-5', name: 'Low-Fat Paneer / Protein Paneer', category: 'Dairy', servingUnit: '100g', servingGrams: 100, calories: 165, protein: 25.0, carbs: 4.0, fat: 5.5, fiber: 0, verified: true },
  { id: 'dr-6', name: 'Curd / Dahi (Plain Whole Milk)', category: 'Dairy', servingUnit: '1 bowl (150g)', servingGrams: 150, calories: 98, protein: 5.2, carbs: 6.8, fat: 4.5, fiber: 0, verified: true },
  { id: 'dr-7', name: 'Low-Fat Curd / Dahi', category: 'Dairy', servingUnit: '1 bowl (150g)', servingGrams: 150, calories: 75, protein: 6.0, carbs: 7.0, fat: 2.0, fiber: 0, verified: true },
  { id: 'dr-8', name: 'Greek Yogurt (0% Fat Plain - Epigamia/Nestle)', category: 'Dairy', servingUnit: '1 cup (100g)', servingGrams: 100, calories: 60, protein: 10.0, carbs: 4.5, fat: 0.2, fiber: 0, verified: true },
  { id: 'dr-9', name: 'Greek Yogurt (Strawberry/Blueberry Flavored)', category: 'Dairy', servingUnit: '1 cup (100g)', servingGrams: 100, calories: 95, protein: 7.5, carbs: 14.0, fat: 1.0, fiber: 0.5, verified: true },
  { id: 'dr-10', name: 'Pure Desi Ghee (Clarified Butter)', category: 'Dairy', servingUnit: '1 tbsp (15g)', servingGrams: 15, calories: 135, protein: 0, carbs: 0, fat: 15.0, fiber: 0, verified: true },
  { id: 'dr-11', name: 'Amul Butter (Salted)', category: 'Dairy', servingUnit: '1 cube (10g)', servingGrams: 10, calories: 72, protein: 0.1, carbs: 0.1, fat: 8.1, fiber: 0, verified: true },
  { id: 'dr-12', name: 'Cheese Slice (Processed - Amul/Britannia)', category: 'Dairy', servingUnit: '1 slice (20g)', servingGrams: 20, calories: 62, protein: 4.0, carbs: 0.5, fat: 5.0, fiber: 0, verified: true },
  { id: 'dr-13', name: 'Mozzarella Cheese (Diced/Shredded)', category: 'Dairy', servingUnit: '50g', servingGrams: 50, calories: 150, protein: 11.0, carbs: 1.5, fat: 11.0, fiber: 0, verified: true },
  { id: 'dr-14', name: 'Cheddar Cheese Block', category: 'Dairy', servingUnit: '30g', servingGrams: 30, calories: 120, protein: 7.5, carbs: 0.5, fat: 10.0, fiber: 0, verified: true },
  { id: 'dr-15', name: 'Buttermilk / Chaas (Spiced Masala)', category: 'Dairy', servingUnit: '1 glass (250ml)', servingGrams: 250, calories: 55, protein: 3.5, carbs: 5.0, fat: 2.2, fiber: 0, verified: true },
  { id: 'dr-16', name: 'Sweet Lassi (Traditional)', category: 'Dairy', servingUnit: '1 glass (300ml)', servingGrams: 300, calories: 260, protein: 7.5, carbs: 36.0, fat: 9.5, fiber: 0, verified: true },
  { id: 'dr-17', name: 'Salted Jeera Lassi', category: 'Dairy', servingUnit: '1 glass (300ml)', servingGrams: 300, calories: 150, protein: 7.0, carbs: 12.0, fat: 7.0, fiber: 0, verified: true },
  { id: 'dr-18', name: 'Amul Fresh Cream (25% Milk Fat)', category: 'Dairy', servingUnit: '2 tbsp (30ml)', servingGrams: 30, calories: 75, protein: 0.8, carbs: 1.2, fat: 7.5, fiber: 0, verified: true },
  { id: 'dr-19', name: 'Milk Powder (Skimmed)', category: 'Dairy', servingUnit: '2 tbsp (25g)', servingGrams: 25, calories: 90, protein: 8.8, carbs: 13.0, fat: 0.3, fiber: 0, verified: true },
  { id: 'dr-20', name: 'Condensed Milk (Sweetened Amul Mithai Mate)', category: 'Dairy', servingUnit: '2 tbsp (40g)', servingGrams: 40, calories: 130, protein: 3.0, carbs: 22.0, fat: 3.4, fiber: 0, verified: true },
  { id: 'dr-21', name: 'Almond Milk (Unsweetened)', category: 'Dairy', servingUnit: '1 glass (250ml)', servingGrams: 250, calories: 35, protein: 1.2, carbs: 1.0, fat: 3.0, fiber: 0.8, verified: true },
  { id: 'dr-22', name: 'Soy Milk (Plain Unsweetened)', category: 'Dairy', servingUnit: '1 glass (250ml)', servingGrams: 250, calories: 105, protein: 8.0, carbs: 4.0, fat: 5.0, fiber: 1.5, verified: true },
  { id: 'dr-23', name: 'Oat Milk (Unsweetened)', category: 'Dairy', servingUnit: '1 glass (250ml)', servingGrams: 250, calories: 120, protein: 3.0, carbs: 16.0, fat: 4.5, fiber: 2.0, verified: true },
  { id: 'dr-24', name: 'Ricotta / Whey Cottage Cheese', category: 'Dairy', servingUnit: '100g', servingGrams: 100, calories: 140, protein: 11.5, carbs: 4.0, fat: 9.0, fiber: 0, verified: true },
  { id: 'dr-25', name: 'Kulfi (Traditional Malai Dairy Dessert)', category: 'Dairy', servingUnit: '1 stick (80g)', servingGrams: 80, calories: 180, protein: 4.5, carbs: 22.0, fat: 8.5, fiber: 0, verified: true },

  // ==========================================
  // 6. EGGS (15 items)
  // ==========================================
  { id: 'eg-1', name: 'Whole Boiled Egg', category: 'Eggs', servingUnit: '1 large egg (50g)', servingGrams: 50, calories: 74, protein: 6.3, carbs: 0.4, fat: 5.0, fiber: 0, verified: true },
  { id: 'eg-2', name: 'Egg White (Boiled)', category: 'Eggs', servingUnit: '1 egg white (33g)', servingGrams: 33, calories: 17, protein: 3.6, carbs: 0.2, fat: 0.1, fiber: 0, verified: true },
  { id: 'eg-3', name: 'Scrambled Eggs (2 Whole Eggs with Butter)', category: 'Eggs', servingUnit: '2 eggs (120g)', servingGrams: 120, calories: 195, protein: 13.0, carbs: 1.2, fat: 15.0, fiber: 0, verified: true },
  { id: 'eg-4', name: 'Egg Omelette (2 Eggs + Onion, Tomato, Green Chilli)', category: 'Eggs', servingUnit: '1 omelette (140g)', servingGrams: 140, calories: 210, protein: 14.0, carbs: 4.0, fat: 15.5, fiber: 0.8, verified: true },
  { id: 'eg-5', name: 'Egg White Omelette (4 Whites + Veggies)', category: 'Eggs', servingUnit: '1 omelette (160g)', servingGrams: 160, calories: 115, protein: 16.5, carbs: 4.5, fat: 2.5, fiber: 1.0, verified: true },
  { id: 'eg-6', name: 'Egg Bhurji / Indian Scramble (3 Eggs with Masala)', category: 'Eggs', servingUnit: '1 plate (180g)', servingGrams: 180, calories: 275, protein: 19.5, carbs: 5.0, fat: 19.0, fiber: 1.2, verified: true },
  { id: 'eg-7', name: 'Sunny Side Up / Half Fry Egg (1 Egg in Ghee)', category: 'Eggs', servingUnit: '1 egg (60g)', servingGrams: 60, calories: 95, protein: 6.3, carbs: 0.4, fat: 7.5, fiber: 0, verified: true },
  { id: 'eg-8', name: 'Poached Egg', category: 'Eggs', servingUnit: '1 large egg (50g)', servingGrams: 50, calories: 72, protein: 6.3, carbs: 0.4, fat: 4.8, fiber: 0, verified: true },
  { id: 'eg-9', name: 'Egg Roll / Kolkata Kathi Roll (1 Paratha + 2 Eggs)', category: 'Eggs', servingUnit: '1 roll (200g)', servingGrams: 200, calories: 380, protein: 17.0, carbs: 38.0, fat: 18.0, fiber: 2.5, verified: true },
  { id: 'eg-10', name: 'Egg Sandwich (2 Whole Wheat Slices + 2 Boiled Eggs)', category: 'Eggs', servingUnit: '1 sandwich (180g)', servingGrams: 180, calories: 310, protein: 18.5, carbs: 32.0, fat: 12.0, fiber: 3.5, verified: true },
  { id: 'eg-11', name: 'Egg White Bhurji (5 Whites + Spices & Veggies)', category: 'Eggs', servingUnit: '1 plate (200g)', servingGrams: 200, calories: 145, protein: 20.0, carbs: 5.5, fat: 3.5, fiber: 1.5, verified: true },
  { id: 'eg-12', name: 'Egg Drop Soup (Chicken / Veg Broth with Egg)', category: 'Eggs', servingUnit: '1 bowl (250ml)', servingGrams: 250, calories: 120, protein: 8.5, carbs: 6.0, fat: 6.5, fiber: 0.5, verified: true },
  { id: 'eg-13', name: 'Masala Boiled Eggs (3 Sliced Eggs with Chaat Masala)', category: 'Eggs', servingUnit: '3 eggs (150g)', servingGrams: 150, calories: 225, protein: 19.0, carbs: 1.5, fat: 15.0, fiber: 0.2, verified: true },
  { id: 'eg-14', name: 'Quail Eggs (Boiled)', category: 'Eggs', servingUnit: '5 eggs (50g)', servingGrams: 50, calories: 79, protein: 6.5, carbs: 0.2, fat: 5.5, fiber: 0, verified: true },
  { id: 'eg-15', name: 'Egg Salad (3 Chopped Eggs + Light Mayo & Mustard)', category: 'Eggs', servingUnit: '1 bowl (180g)', servingGrams: 180, calories: 280, protein: 19.0, carbs: 3.0, fat: 21.0, fiber: 0.4, verified: true },

  // ==========================================
  // 7. CHICKEN (25 items)
  // ==========================================
  { id: 'ch-1', name: 'Chicken Breast (Raw Skinless Boneless)', category: 'Chicken', servingUnit: '100g', servingGrams: 100, calories: 120, protein: 24.5, carbs: 0, fat: 2.0, fiber: 0, verified: true },
  { id: 'ch-2', name: 'Chicken Breast (Grilled / Cooked)', category: 'Chicken', servingUnit: '100g', servingGrams: 100, calories: 165, protein: 31.0, carbs: 0, fat: 3.6, fiber: 0, verified: true },
  { id: 'ch-3', name: 'Boiled Chicken Breast (Shredded Plain)', category: 'Chicken', servingUnit: '100g', servingGrams: 100, calories: 150, protein: 30.5, carbs: 0, fat: 2.8, fiber: 0, verified: true },
  { id: 'ch-4', name: 'Chicken Thigh (Skinless Boneless Grilled)', category: 'Chicken', servingUnit: '100g', servingGrams: 100, calories: 205, protein: 26.0, carbs: 0, fat: 10.5, fiber: 0, verified: true },
  { id: 'ch-5', name: 'Chicken Drumstick / Tangdi (Tandoori Roasted)', category: 'Chicken', servingUnit: '1 piece (110g)', servingGrams: 110, calories: 175, protein: 22.0, carbs: 1.5, fat: 8.5, fiber: 0, verified: true },
  { id: 'ch-6', name: 'Chicken Keema (Minced Breast Lean Cooked)', category: 'Chicken', servingUnit: '150g', servingGrams: 150, calories: 235, protein: 36.0, carbs: 3.5, fat: 8.0, fiber: 0.5, verified: true },
  { id: 'ch-7', name: 'Chicken Tikka (Tandoori Boneless 6 Pcs)', category: 'Chicken', servingUnit: '1 plate (160g)', servingGrams: 160, calories: 240, protein: 36.0, carbs: 3.0, fat: 8.5, fiber: 0.8, verified: true },
  { id: 'ch-8', name: 'Chicken Malai Tikka (Cream & Cashew Marinated)', category: 'Chicken', servingUnit: '1 plate (180g)', servingGrams: 180, calories: 340, protein: 34.0, carbs: 5.0, fat: 20.0, fiber: 0.5, verified: true },
  { id: 'ch-9', name: 'Chicken Seekh Kabab (Grilled Minced)', category: 'Chicken', servingUnit: '2 skewers (140g)', servingGrams: 140, calories: 250, protein: 28.0, carbs: 4.5, fat: 13.0, fiber: 1.0, verified: true },
  { id: 'ch-10', name: 'Home-Style Chicken Curry (Gravy + Chicken)', category: 'Chicken', servingUnit: '1 bowl (220g)', servingGrams: 220, calories: 290, protein: 32.0, carbs: 6.0, fat: 14.5, fiber: 1.8, verified: true },
  { id: 'ch-11', name: 'Butter Chicken (Restaurant Style)', category: 'Chicken', servingUnit: '1 bowl (220g)', servingGrams: 220, calories: 420, protein: 30.0, carbs: 12.0, fat: 28.0, fiber: 1.5, verified: true },
  { id: 'ch-12', name: 'Chicken Shawarma (Meat Only in Spices)', category: 'Chicken', servingUnit: '150g', servingGrams: 150, calories: 260, protein: 31.0, carbs: 3.0, fat: 13.0, fiber: 0.5, verified: true },
  { id: 'ch-13', name: 'Chicken Biryani (Hyderabadi Dumpukht - 1 Plate)', category: 'Chicken', servingUnit: '1 plate (350g)', servingGrams: 350, calories: 540, protein: 35.0, carbs: 62.0, fat: 16.0, fiber: 3.2, verified: true },
  { id: 'ch-14', name: 'Grilled Chicken Caesar Salad', category: 'Chicken', servingUnit: '1 large bowl (250g)', servingGrams: 250, calories: 280, protein: 32.0, carbs: 8.0, fat: 13.0, fiber: 3.0, verified: true },
  { id: 'ch-15', name: 'Chicken Sausage (Cooked)', category: 'Chicken', servingUnit: '2 links (100g)', servingGrams: 100, calories: 170, protein: 18.0, carbs: 2.5, fat: 9.5, fiber: 0, verified: true },
  { id: 'ch-16', name: 'Chicken Nuggets (Fried)', category: 'Chicken', servingUnit: '6 pieces (120g)', servingGrams: 120, calories: 320, protein: 18.0, carbs: 20.0, fat: 18.0, fiber: 1.0, verified: true },
  { id: 'ch-17', name: 'KFC Style Fried Chicken (1 Thigh Piece)', category: 'Chicken', servingUnit: '1 piece (120g)', servingGrams: 120, calories: 360, protein: 22.0, carbs: 15.0, fat: 24.0, fiber: 0.8, verified: true },
  { id: 'ch-18', name: 'Chicken Stir-Fry with Broccoli & Garlic', category: 'Chicken', servingUnit: '1 bowl (220g)', servingGrams: 220, calories: 230, protein: 32.0, carbs: 8.0, fat: 7.5, fiber: 3.5, verified: true },
  { id: 'ch-19', name: 'Chicken Clear Soup (Shredded Chicken Broth)', category: 'Chicken', servingUnit: '1 bowl (250ml)', servingGrams: 250, calories: 110, protein: 16.0, carbs: 3.0, fat: 3.5, fiber: 0.5, verified: true },
  { id: 'ch-20', name: 'Chicken Momos (Steamed - 6 pieces)', category: 'Chicken', servingUnit: '6 pieces (150g)', servingGrams: 150, calories: 240, protein: 16.0, carbs: 28.0, fat: 6.5, fiber: 1.5, verified: true },
  { id: 'ch-21', name: 'Chicken Kathi Roll (Whole Wheat Roti + Chicken)', category: 'Chicken', servingUnit: '1 roll (200g)', servingGrams: 200, calories: 360, protein: 28.0, carbs: 34.0, fat: 12.0, fiber: 3.0, verified: true },
  { id: 'ch-22', name: 'Chilli Chicken (Indo-Chinese Dry)', category: 'Chicken', servingUnit: '1 plate (180g)', servingGrams: 180, calories: 310, protein: 28.0, carbs: 16.0, fat: 14.5, fiber: 2.0, verified: true },
  { id: 'ch-23', name: 'Chicken Ham / Salami Slices', category: 'Chicken', servingUnit: '4 slices (60g)', servingGrams: 60, calories: 85, protein: 12.5, carbs: 1.5, fat: 3.0, fiber: 0, verified: true },
  { id: 'ch-24', name: 'Chicken Liver (Cooked in Spices)', category: 'Chicken', servingUnit: '100g', servingGrams: 100, calories: 165, protein: 24.0, carbs: 1.0, fat: 6.5, fiber: 0, verified: true },
  { id: 'ch-25', name: 'Roast Whole Chicken (Herb Seasoned)', category: 'Chicken', servingUnit: '150g portion', servingGrams: 150, calories: 270, protein: 36.0, carbs: 0, fat: 13.0, fiber: 0, verified: true },

  // ==========================================
  // 8. FISH & SEAFOOD (20 items)
  // ==========================================
  { id: 'fs-1', name: 'Rohu Fish (Bengali Rohu Steamed/Raw)', category: 'Fish', servingUnit: '100g', servingGrams: 100, calories: 110, protein: 20.0, carbs: 0, fat: 3.0, fiber: 0, verified: true },
  { id: 'fs-2', name: 'Rohu Fish Curry (Mustard Gravy Macher Jhol)', category: 'Fish', servingUnit: '1 bowl (200g)', servingGrams: 200, calories: 230, protein: 24.0, carbs: 4.5, fat: 12.5, fiber: 1.0, verified: true },
  { id: 'fs-3', name: 'Katla Fish (Raw/Cooked)', category: 'Fish', servingUnit: '100g', servingGrams: 100, calories: 115, protein: 19.5, carbs: 0, fat: 3.5, fiber: 0, verified: true },
  { id: 'fs-4', name: 'Salmon Fillet (Atlantic Grilled)', category: 'Fish', servingUnit: '1 fillet (150g)', servingGrams: 150, calories: 310, protein: 34.0, carbs: 0, fat: 18.0, fiber: 0, verified: true },
  { id: 'fs-5', name: 'Tuna (Canned in Water / Light Brine)', category: 'Fish', servingUnit: '1 can drained (120g)', servingGrams: 120, calories: 130, protein: 29.0, carbs: 0, fat: 1.2, fiber: 0, verified: true },
  { id: 'fs-6', name: 'Tuna (Canned in Olive Oil)', category: 'Fish', servingUnit: '1 can (120g)', servingGrams: 120, calories: 220, protein: 28.0, carbs: 0, fat: 11.5, fiber: 0, verified: true },
  { id: 'fs-7', name: 'Basa Fish Fillet (Grilled Plain)', category: 'Fish', servingUnit: '100g', servingGrams: 100, calories: 95, protein: 17.5, carbs: 0, fat: 2.5, fiber: 0, verified: true },
  { id: 'fs-8', name: 'Pomfret (Tandoori Roasted Whole)', category: 'Fish', servingUnit: '1 fish (180g)', servingGrams: 180, calories: 220, protein: 32.0, carbs: 2.0, fat: 9.0, fiber: 0, verified: true },
  { id: 'fs-9', name: 'Surmai / King Fish Steak (Pan-Seared)', category: 'Fish', servingUnit: '150g', servingGrams: 150, calories: 210, protein: 33.0, carbs: 1.0, fat: 7.8, fiber: 0, verified: true },
  { id: 'fs-10', name: 'Bangda / Indian Mackerel (Grilled with Spices)', category: 'Fish', servingUnit: '1 fish (140g)', servingGrams: 140, calories: 250, protein: 26.0, carbs: 1.0, fat: 15.5, fiber: 0, verified: true },
  { id: 'fs-11', name: 'Hilsa Fish / Ilish (Steamed Shorshe Ilish)', category: 'Fish', servingUnit: '1 piece (150g)', servingGrams: 150, calories: 340, protein: 28.0, carbs: 3.0, fat: 24.0, fiber: 0.5, verified: true },
  { id: 'fs-12', name: 'Prawns / Shrimps (Boiled / Grilled Garlic)', category: 'Fish', servingUnit: '100g', servingGrams: 100, calories: 100, protein: 23.0, carbs: 0.5, fat: 1.0, fiber: 0, verified: true },
  { id: 'fs-13', name: 'Prawn Masala Curry (Goan / Kerala Style)', category: 'Fish', servingUnit: '1 bowl (200g)', servingGrams: 200, calories: 240, protein: 25.0, carbs: 7.0, fat: 12.0, fiber: 1.5, verified: true },
  { id: 'fs-14', name: 'Tilapia Fillet (Pan Seared)', category: 'Fish', servingUnit: '120g', servingGrams: 120, calories: 130, protein: 26.0, carbs: 0, fat: 2.8, fiber: 0, verified: true },
  { id: 'fs-15', name: 'Amritsari Fish Fry (Gram Flour Batter Fried)', category: 'Fish', servingUnit: '1 plate (150g)', servingGrams: 150, calories: 290, protein: 26.0, carbs: 9.0, fat: 16.5, fiber: 1.2, verified: true },
  { id: 'fs-16', name: 'Crab Meat (Boiled/Steamed)', category: 'Fish', servingUnit: '100g', servingGrams: 100, calories: 90, protein: 19.0, carbs: 0, fat: 1.2, fiber: 0, verified: true },
  { id: 'fs-17', name: 'Squid / Calamari (Grilled in Olive Oil)', category: 'Fish', servingUnit: '100g', servingGrams: 100, calories: 110, protein: 18.0, carbs: 3.0, fat: 2.5, fiber: 0, verified: true },
  { id: 'fs-18', name: 'Cod Fish Fillet (Baked)', category: 'Fish', servingUnit: '120g', servingGrams: 120, calories: 105, protein: 24.0, carbs: 0, fat: 0.9, fiber: 0, verified: true },
  { id: 'fs-19', name: 'Fish Tikka (Tandoori Fish 6 Pcs)', category: 'Fish', servingUnit: '1 plate (160g)', servingGrams: 160, calories: 210, protein: 30.0, carbs: 3.5, fat: 7.5, fiber: 0.6, verified: true },
  { id: 'fs-20', name: 'Fish Biryani (Spiced Basmati & Fish)', category: 'Fish', servingUnit: '1 plate (350g)', servingGrams: 350, calories: 480, protein: 30.0, carbs: 64.0, fat: 11.5, fiber: 2.8, verified: true },

  // ==========================================
  // 9. RICE & GRAINS (20 items)
  // ==========================================
  { id: 'rc-1', name: 'Boiled White Rice (Basmati / Sona Masoori)', category: 'Rice', servingUnit: '1 bowl (150g)', servingGrams: 150, calories: 195, protein: 4.1, carbs: 42.5, fat: 0.5, fiber: 0.9, verified: true },
  { id: 'rc-2', name: 'Brown Rice (Cooked Whole Grain)', category: 'Rice', servingUnit: '1 bowl (150g)', servingGrams: 150, calories: 165, protein: 3.8, carbs: 35.0, fat: 1.4, fiber: 2.8, verified: true },
  { id: 'rc-3', name: 'Jeera Rice (Cooked in Light Cumin & Ghee)', category: 'Rice', servingUnit: '1 bowl (160g)', servingGrams: 160, calories: 230, protein: 4.3, carbs: 44.0, fat: 3.8, fiber: 1.0, verified: true },
  { id: 'rc-4', name: 'Curd Rice (South Indian Thayir Sadam)', category: 'Rice', servingUnit: '1 bowl (200g)', servingGrams: 200, calories: 240, protein: 6.5, carbs: 38.0, fat: 6.5, fiber: 1.2, verified: true },
  { id: 'rc-5', name: 'Lemon Rice (South Indian Chitranna with Peanuts)', category: 'Rice', servingUnit: '1 bowl (180g)', servingGrams: 180, calories: 260, protein: 5.5, carbs: 44.0, fat: 7.0, fiber: 2.0, verified: true },
  { id: 'rc-6', name: 'Vegetable Pulao (With Peas, Carrots & Spices)', category: 'Rice', servingUnit: '1 plate (200g)', servingGrams: 200, calories: 250, protein: 5.8, carbs: 46.0, fat: 5.0, fiber: 3.0, verified: true },
  { id: 'rc-7', name: 'Veg Biryani (Dum Spiced Basmati & Vegetables)', category: 'Rice', servingUnit: '1 plate (300g)', servingGrams: 300, calories: 410, protein: 9.5, carbs: 68.0, fat: 11.0, fiber: 4.5, verified: true },
  { id: 'rc-8', name: 'Egg Fried Rice (Chinese Style)', category: 'Rice', servingUnit: '1 plate (220g)', servingGrams: 220, calories: 340, protein: 12.0, carbs: 48.0, fat: 11.0, fiber: 2.0, verified: true },
  { id: 'rc-9', name: 'Veg Fried Rice (Indo-Chinese)', category: 'Rice', servingUnit: '1 plate (220g)', servingGrams: 220, calories: 310, protein: 6.0, carbs: 54.0, fat: 8.0, fiber: 2.8, verified: true },
  { id: 'rc-10', name: 'Chicken Fried Rice', category: 'Rice', servingUnit: '1 plate (250g)', servingGrams: 250, calories: 420, protein: 24.0, carbs: 52.0, fat: 13.0, fiber: 2.2, verified: true },
  { id: 'rc-11', name: 'Moong Dal Khichdi (Comfort Rice-Lentil Stew)', category: 'Rice', servingUnit: '1 bowl (250g)', servingGrams: 250, calories: 280, protein: 10.0, carbs: 48.0, fat: 5.0, fiber: 4.2, verified: true },
  { id: 'rc-12', name: 'Puffed Rice / Murmura (Raw Dry)', category: 'Rice', servingUnit: '2 cups (30g)', servingGrams: 30, calories: 115, protein: 2.2, carbs: 26.0, fat: 0.2, fiber: 1.0, verified: true },
  { id: 'rc-13', name: 'Poha / Flattened Rice (Dry Raw Flakes)', category: 'Rice', servingUnit: '50g raw', servingGrams: 50, calories: 180, protein: 3.5, carbs: 39.0, fat: 0.6, fiber: 1.5, verified: true },
  { id: 'rc-14', name: 'Quinoa (Cooked)', category: 'Rice', servingUnit: '1 cup (185g)', servingGrams: 185, calories: 222, protein: 8.1, carbs: 39.0, fat: 3.5, fiber: 5.2, verified: true },
  { id: 'rc-15', name: 'Jasmine Rice (Cooked Steamed)', category: 'Rice', servingUnit: '1 bowl (150g)', servingGrams: 150, calories: 190, protein: 3.8, carbs: 42.0, fat: 0.4, fiber: 0.6, verified: true },
  { id: 'rc-16', name: 'Sambar Rice (South Indian Bisibelebath)', category: 'Rice', servingUnit: '1 plate (250g)', servingGrams: 250, calories: 310, protein: 9.0, carbs: 54.0, fat: 6.0, fiber: 5.0, verified: true },
  { id: 'rc-17', name: 'Tomato Rice (Spiced South Indian Thakkali Sadam)', category: 'Rice', servingUnit: '1 bowl (180g)', servingGrams: 180, calories: 245, protein: 4.8, carbs: 43.0, fat: 6.0, fiber: 2.2, verified: true },
  { id: 'rc-18', name: 'Red Rice / Matta Rice (Kerala Cooked)', category: 'Rice', servingUnit: '1 bowl (150g)', servingGrams: 150, calories: 170, protein: 4.0, carbs: 36.0, fat: 1.1, fiber: 3.2, verified: true },
  { id: 'rc-19', name: 'Schezwan Fried Rice (Spicy Indo-Chinese)', category: 'Rice', servingUnit: '1 plate (220g)', servingGrams: 220, calories: 330, protein: 6.2, carbs: 52.0, fat: 10.5, fiber: 2.5, verified: true },
  { id: 'rc-20', name: 'Mutton Biryani (Rich Dum Basmati)', category: 'Rice', servingUnit: '1 plate (350g)', servingGrams: 350, calories: 590, protein: 32.0, carbs: 60.0, fat: 24.0, fiber: 3.0, verified: true },

  // ==========================================
  // 10. BREAD & ROTIS (25 items)
  // ==========================================
  { id: 'br-1', name: 'Whole Wheat Roti / Phulka (No Ghee)', category: 'Bread', servingUnit: '1 roti (35g)', servingGrams: 35, calories: 104, protein: 3.5, carbs: 20.0, fat: 0.8, fiber: 2.7, verified: true },
  { id: 'br-2', name: 'Chapati (with 1/2 tsp Desi Ghee)', category: 'Bread', servingUnit: '1 chapati (40g)', servingGrams: 40, calories: 125, protein: 3.6, carbs: 20.0, fat: 3.0, fiber: 2.8, verified: true },
  { id: 'br-3', name: 'Plain Paratha (Shallow Fried in Oil/Ghee)', category: 'Bread', servingUnit: '1 paratha (60g)', servingGrams: 60, calories: 210, protein: 4.5, carbs: 28.0, fat: 9.0, fiber: 2.5, verified: true },
  { id: 'br-4', name: 'Aloo Paratha (Stuffed Spiced Potato)', category: 'Bread', servingUnit: '1 paratha (120g)', servingGrams: 120, calories: 280, protein: 6.0, carbs: 42.0, fat: 9.8, fiber: 4.0, verified: true },
  { id: 'br-5', name: 'Paneer Paratha (High Protein Stuffed)', category: 'Bread', servingUnit: '1 paratha (130g)', servingGrams: 130, calories: 330, protein: 14.5, carbs: 36.0, fat: 14.0, fiber: 3.5, verified: true },
  { id: 'br-6', name: 'Gobi Paratha (Stuffed Spiced Cauliflower)', category: 'Bread', servingUnit: '1 paratha (120g)', servingGrams: 120, calories: 250, protein: 6.5, carbs: 36.0, fat: 8.5, fiber: 4.5, verified: true },
  { id: 'br-7', name: 'Tandoori Roti (Whole Wheat Restaurant Style)', category: 'Bread', servingUnit: '1 roti (50g)', servingGrams: 50, calories: 130, protein: 4.5, carbs: 26.0, fat: 0.8, fiber: 3.2, verified: true },
  { id: 'br-8', name: 'Butter Tandoori Roti', category: 'Bread', servingUnit: '1 roti (55g)', servingGrams: 55, calories: 165, protein: 4.5, carbs: 26.0, fat: 4.8, fiber: 3.2, verified: true },
  { id: 'br-9', name: 'Plain Naan (Refined Flour)', category: 'Bread', servingUnit: '1 naan (90g)', servingGrams: 90, calories: 260, protein: 7.5, carbs: 46.0, fat: 4.5, fiber: 2.0, verified: true },
  { id: 'br-10', name: 'Butter Naan', category: 'Bread', servingUnit: '1 naan (100g)', servingGrams: 100, calories: 310, protein: 7.8, carbs: 46.0, fat: 10.0, fiber: 2.0, verified: true },
  { id: 'br-11', name: 'Garlic Naan (with Butter & Coriander)', category: 'Bread', servingUnit: '1 naan (100g)', servingGrams: 100, calories: 320, protein: 8.0, carbs: 47.0, fat: 10.5, fiber: 2.2, verified: true },
  { id: 'br-12', name: 'Missi Roti (Gram Flour & Wheat Spiced)', category: 'Bread', servingUnit: '1 roti (50g)', servingGrams: 50, calories: 145, protein: 6.0, carbs: 23.0, fat: 3.2, fiber: 3.8, verified: true },
  { id: 'br-13', name: 'Makki Ki Roti (Cornmeal Flatbread)', category: 'Bread', servingUnit: '1 roti (50g)', servingGrams: 50, calories: 155, protein: 3.5, carbs: 28.0, fat: 3.0, fiber: 3.5, verified: true },
  { id: 'br-14', name: 'Bajra Roti (Pearl Millet Flatbread - High Iron)', category: 'Bread', servingUnit: '1 roti (50g)', servingGrams: 50, calories: 140, protein: 4.2, carbs: 25.0, fat: 2.2, fiber: 4.0, verified: true },
  { id: 'br-15', name: 'Jowar Roti (Sorghum Flatbread - Gluten Free)', category: 'Bread', servingUnit: '1 roti (50g)', servingGrams: 50, calories: 135, protein: 4.0, carbs: 27.0, fat: 1.2, fiber: 3.8, verified: true },
  { id: 'br-16', name: 'Rumali Roti', category: 'Bread', servingUnit: '1 large roti (70g)', servingGrams: 70, calories: 200, protein: 5.5, carbs: 38.0, fat: 2.8, fiber: 1.5, verified: true },
  { id: 'br-17', name: 'White Bread Slice', category: 'Bread', servingUnit: '1 slice (30g)', servingGrams: 30, calories: 75, protein: 2.4, carbs: 14.5, fat: 0.9, fiber: 0.8, verified: true },
  { id: 'br-18', name: '100% Whole Wheat Bread Slice', category: 'Bread', servingUnit: '1 slice (35g)', servingGrams: 35, calories: 82, protein: 3.8, carbs: 14.0, fat: 1.1, fiber: 2.4, verified: true },
  { id: 'br-19', name: 'Multigrain Bread Slice', category: 'Bread', servingUnit: '1 slice (35g)', servingGrams: 35, calories: 85, protein: 4.2, carbs: 14.0, fat: 1.4, fiber: 2.8, verified: true },
  { id: 'br-20', name: 'Pav / Dinner Bun (Ladi Pav)', category: 'Bread', servingUnit: '1 piece (40g)', servingGrams: 40, calories: 115, protein: 3.2, carbs: 22.0, fat: 1.5, fiber: 1.0, verified: true },
  { id: 'br-21', name: 'Bhatura (Deep Fried Bread for Chole)', category: 'Bread', servingUnit: '1 bhatura (80g)', servingGrams: 80, calories: 290, protein: 5.5, carbs: 34.0, fat: 14.5, fiber: 1.2, verified: true },
  { id: 'br-22', name: 'Puri (Deep Fried Wheat Bread)', category: 'Bread', servingUnit: '1 puri (30g)', servingGrams: 30, calories: 120, protein: 2.1, carbs: 15.0, fat: 5.8, fiber: 1.2, verified: true },
  { id: 'br-23', name: 'Pita Bread (Whole Wheat Pocket)', category: 'Bread', servingUnit: '1 pocket (60g)', servingGrams: 60, calories: 160, protein: 6.0, carbs: 32.0, fat: 1.2, fiber: 3.0, verified: true },
  { id: 'br-24', name: 'Tortilla Wrap (Flour / Corn)', category: 'Bread', servingUnit: '1 large wrap (60g)', servingGrams: 60, calories: 175, protein: 4.5, carbs: 30.0, fat: 4.0, fiber: 2.0, verified: true },
  { id: 'br-25', name: 'Sourdough Bread Slice', category: 'Bread', servingUnit: '1 slice (50g)', servingGrams: 50, calories: 120, protein: 4.5, carbs: 24.0, fat: 0.8, fiber: 1.6, verified: true },

  // ==========================================
  // 11. PROTEIN FOODS (25 items)
  // ==========================================
  { id: 'pr-1', name: 'Soya Chunks (Nutrela Raw Dry)', category: 'Protein Foods', servingUnit: '50g raw', servingGrams: 50, calories: 172, protein: 26.0, carbs: 16.5, fat: 0.3, fiber: 6.5, verified: true },
  { id: 'pr-2', name: 'Soya Granules (Raw Dry)', category: 'Protein Foods', servingUnit: '50g raw', servingGrams: 50, calories: 170, protein: 26.0, carbs: 16.0, fat: 0.3, fiber: 6.5, verified: true },
  { id: 'pr-3', name: 'Tofu / Soya Paneer (Firm Block)', category: 'Protein Foods', servingUnit: '100g', servingGrams: 100, calories: 144, protein: 17.3, carbs: 2.8, fat: 8.7, fiber: 2.3, verified: true },
  { id: 'pr-4', name: 'Whey Protein Isolate (1 Scoop - Generic)', category: 'Protein Foods', servingUnit: '1 scoop (30g)', servingGrams: 30, calories: 120, protein: 27.0, carbs: 1.0, fat: 0.8, fiber: 0, verified: true },
  { id: 'pr-5', name: 'Whey Protein Concentrate (1 Scoop - Generic)', category: 'Protein Foods', servingUnit: '1 scoop (33g)', servingGrams: 33, calories: 130, protein: 24.0, carbs: 3.0, fat: 2.0, fiber: 0, verified: true },
  { id: 'pr-6', name: 'Plant Protein Powder (Pea & Brown Rice Isolate)', category: 'Protein Foods', servingUnit: '1 scoop (33g)', servingGrams: 33, calories: 125, protein: 25.0, carbs: 2.5, fat: 1.5, fiber: 1.5, verified: true },
  { id: 'pr-7', name: 'Casein Protein (Slow Digesting Micellar)', category: 'Protein Foods', servingUnit: '1 scoop (33g)', servingGrams: 33, calories: 120, protein: 24.0, carbs: 2.0, fat: 1.0, fiber: 0, verified: true },
  { id: 'pr-8', name: 'Natural Peanut Butter (100% Peanuts)', category: 'Protein Foods', servingUnit: '1 tbsp (32g)', servingGrams: 32, calories: 190, protein: 8.5, carbs: 6.5, fat: 16.0, fiber: 2.5, verified: true },
  { id: 'pr-9', name: 'Almond Butter (100% Pure Almonds)', category: 'Protein Foods', servingUnit: '1 tbsp (30g)', servingGrams: 30, calories: 195, protein: 7.0, carbs: 5.5, fat: 17.5, fiber: 3.0, verified: true },
  { id: 'pr-10', name: 'Roasted Chana Sattu Flour (Bihari Superfood)', category: 'Protein Foods', servingUnit: '4 tbsp (50g)', servingGrams: 50, calories: 195, protein: 12.5, carbs: 30.0, fat: 2.8, fiber: 8.5, verified: true },
  { id: 'pr-11', name: 'Boiled Kala Chana (Black Bengal Gram)', category: 'Protein Foods', servingUnit: '1 bowl (150g)', servingGrams: 150, calories: 190, protein: 11.5, carbs: 29.0, fat: 3.0, fiber: 8.0, verified: true },
  { id: 'pr-12', name: 'Boiled Kabuli Chana (White Chickpeas)', category: 'Protein Foods', servingUnit: '1 bowl (150g)', servingGrams: 150, calories: 210, protein: 11.0, carbs: 34.0, fat: 3.5, fiber: 7.5, verified: true },
  { id: 'pr-13', name: 'Boiled Rajma (Red Kidney Beans)', category: 'Protein Foods', servingUnit: '1 bowl (150g)', servingGrams: 150, calories: 185, protein: 12.0, carbs: 31.0, fat: 0.8, fiber: 9.0, verified: true },
  { id: 'pr-14', name: 'Sprouted Green Moong (Raw)', category: 'Protein Foods', servingUnit: '1 bowl (120g)', servingGrams: 120, calories: 125, protein: 9.5, carbs: 21.0, fat: 0.6, fiber: 5.5, verified: true },
  { id: 'pr-15', name: 'Edamame Beans (Boiled Soya Pods)', category: 'Protein Foods', servingUnit: '1 cup (150g)', servingGrams: 150, calories: 188, protein: 18.4, carbs: 13.8, fat: 8.0, fiber: 8.0, verified: true },
  { id: 'pr-16', name: 'Tempeh (Fermented Soya Cake)', category: 'Protein Foods', servingUnit: '100g', servingGrams: 100, calories: 192, protein: 20.3, carbs: 7.6, fat: 10.8, fiber: 4.8, verified: true },
  { id: 'pr-17', name: 'Chia Seeds (Raw)', category: 'Protein Foods', servingUnit: '2 tbsp (25g)', servingGrams: 25, calories: 120, protein: 4.5, carbs: 10.5, fat: 7.5, fiber: 8.5, verified: true },
  { id: 'pr-18', name: 'Hemp Seeds (Shelled Hearts)', category: 'Protein Foods', servingUnit: '2 tbsp (20g)', servingGrams: 20, calories: 110, protein: 6.3, carbs: 1.7, fat: 9.8, fiber: 0.8, verified: true },
  { id: 'pr-19', name: 'Pumpkin Seeds (Raw Pepitas)', category: 'Protein Foods', servingUnit: '1 handful (30g)', servingGrams: 30, calories: 160, protein: 9.0, carbs: 4.0, fat: 13.5, fiber: 2.0, verified: true },
  { id: 'pr-20', name: 'Flaxseeds (Alsi Powder/Raw)', category: 'Protein Foods', servingUnit: '2 tbsp (20g)', servingGrams: 20, calories: 105, protein: 3.8, carbs: 6.0, fat: 8.5, fiber: 5.5, verified: true },
  { id: 'pr-21', name: 'Protein Bar (Generic 20g Protein)', category: 'Protein Foods', servingUnit: '1 bar (60g)', servingGrams: 60, calories: 210, protein: 20.0, carbs: 22.0, fat: 6.0, fiber: 8.0, verified: true },
  { id: 'pr-22', name: 'Protein Lassi / Greek Yogurt Drink (Amul/Epigamia)', category: 'Protein Foods', servingUnit: '1 bottle (200ml)', servingGrams: 200, calories: 130, protein: 15.0, carbs: 12.0, fat: 1.5, fiber: 0, verified: true },
  { id: 'pr-23', name: 'Amul High Protein Buttermilk (15g Protein)', category: 'Protein Foods', servingUnit: '1 tetra pack (200ml)', servingGrams: 200, calories: 85, protein: 15.0, carbs: 4.0, fat: 0.8, fiber: 0, verified: true },
  { id: 'pr-24', name: 'Seitan / Wheat Gluten Protein', category: 'Protein Foods', servingUnit: '100g', servingGrams: 100, calories: 140, protein: 25.0, carbs: 5.0, fat: 2.0, fiber: 1.5, verified: true },
  { id: 'pr-25', name: 'Lentil Protein Pasta / Chickpea Pasta (Cooked)', category: 'Protein Foods', servingUnit: '1 bowl (150g)', servingGrams: 150, calories: 220, protein: 14.0, carbs: 36.0, fat: 2.2, fiber: 6.0, verified: true },

  // ==========================================
  // 12. BEVERAGES (25 items)
  // ==========================================
  { id: 'bv-1', name: 'Indian Masala Chai (with Milk & 1 tsp Sugar)', category: 'Beverages', servingUnit: '1 cup (150ml)', servingGrams: 150, calories: 75, protein: 2.5, carbs: 10.5, fat: 2.8, fiber: 0, verified: true },
  { id: 'bv-2', name: 'Indian Masala Chai (No Sugar / Stevia)', category: 'Beverages', servingUnit: '1 cup (150ml)', servingGrams: 150, calories: 45, protein: 2.5, carbs: 3.5, fat: 2.8, fiber: 0, verified: true },
  { id: 'bv-3', name: 'Black Tea (Plain No Sugar)', category: 'Beverages', servingUnit: '1 cup (200ml)', servingGrams: 200, calories: 2, protein: 0.1, carbs: 0.4, fat: 0, fiber: 0, verified: true },
  { id: 'bv-4', name: 'Green Tea (Organic Brewed)', category: 'Beverages', servingUnit: '1 cup (200ml)', servingGrams: 200, calories: 2, protein: 0.2, carbs: 0.3, fat: 0, fiber: 0, verified: true },
  { id: 'bv-5', name: 'Filter Coffee (South Indian with Milk & Sugar)', category: 'Beverages', servingUnit: '1 tumbler (150ml)', servingGrams: 150, calories: 90, protein: 3.0, carbs: 12.0, fat: 3.2, fiber: 0, verified: true },
  { id: 'bv-6', name: 'Black Coffee (Espresso / Americano No Sugar)', category: 'Beverages', servingUnit: '1 cup (200ml)', servingGrams: 200, calories: 4, protein: 0.3, carbs: 0.5, fat: 0, fiber: 0, verified: true },
  { id: 'bv-7', name: 'Cold Coffee with Milk (Sweetened)', category: 'Beverages', servingUnit: '1 glass (300ml)', servingGrams: 300, calories: 220, protein: 6.5, carbs: 32.0, fat: 7.5, fiber: 0, verified: true },
  { id: 'bv-8', name: 'Fresh Tender Coconut Water (Nariyal Pani)', category: 'Beverages', servingUnit: '1 fresh coconut (250ml)', servingGrams: 250, calories: 48, protein: 0.8, carbs: 11.0, fat: 0.4, fiber: 1.1, verified: true },
  { id: 'bv-9', name: 'Sattu Drink Namkeen (Sattu, Water, Jeera & Lime)', category: 'Beverages', servingUnit: '1 glass (300ml)', servingGrams: 300, calories: 155, protein: 10.0, carbs: 24.0, fat: 2.2, fiber: 6.8, verified: true },
  { id: 'bv-10', name: 'Nimbu Pani / Shikanji (with 1.5 tsp Sugar)', category: 'Beverages', servingUnit: '1 glass (250ml)', servingGrams: 250, calories: 65, protein: 0.2, carbs: 16.0, fat: 0, fiber: 0.3, verified: true },
  { id: 'bv-11', name: 'Diet Coke / Coca-Cola Zero', category: 'Beverages', servingUnit: '1 can (330ml)', servingGrams: 330, calories: 1, protein: 0, carbs: 0, fat: 0, fiber: 0, verified: true },
  { id: 'bv-12', name: 'Fresh Sugarcane Juice (Ganne Ka Ras)', category: 'Beverages', servingUnit: '1 glass (250ml)', servingGrams: 250, calories: 180, protein: 0.5, carbs: 45.0, fat: 0.2, fiber: 0.5, verified: true },
  { id: 'bv-13', name: 'Fresh Orange Juice (No Added Sugar)', category: 'Beverages', servingUnit: '1 glass (250ml)', servingGrams: 250, calories: 112, protein: 1.7, carbs: 26.0, fat: 0.5, fiber: 0.5, verified: true },
  { id: 'bv-14', name: 'Whey Protein Shake in Water (1 Scoop)', category: 'Beverages', servingUnit: '300ml shake', servingGrams: 300, calories: 120, protein: 25.0, carbs: 2.0, fat: 1.0, fiber: 0, verified: true },
  { id: 'bv-15', name: 'Whey Protein Shake in Milk (1 Scoop + 250ml Toned Milk)', category: 'Beverages', servingUnit: '350ml shake', servingGrams: 350, calories: 265, protein: 33.0, carbs: 14.0, fat: 8.5, fiber: 0, verified: true },
  { id: 'bv-16', name: 'Masala Chaas (Spiced Buttermilk)', category: 'Beverages', servingUnit: '1 glass (250ml)', servingGrams: 250, calories: 55, protein: 3.5, carbs: 5.0, fat: 2.2, fiber: 0, verified: true },
  { id: 'bv-17', name: 'Sweet Mango Lassi', category: 'Beverages', servingUnit: '1 glass (300ml)', servingGrams: 300, calories: 280, protein: 7.0, carbs: 44.0, fat: 8.0, fiber: 1.0, verified: true },
  { id: 'bv-18', name: 'Rooh Afza Milk Shake (Rose Syrup with Milk)', category: 'Beverages', servingUnit: '1 glass (250ml)', servingGrams: 250, calories: 210, protein: 6.5, carbs: 32.0, fat: 6.5, fiber: 0, verified: true },
  { id: 'bv-19', name: 'Aam Panna (Raw Mango Summer Cooler)', category: 'Beverages', servingUnit: '1 glass (250ml)', servingGrams: 250, calories: 120, protein: 0.6, carbs: 30.0, fat: 0.2, fiber: 1.2, verified: true },
  { id: 'bv-20', name: 'Red Bull Energy Drink (Regular)', category: 'Beverages', servingUnit: '1 can (250ml)', servingGrams: 250, calories: 115, protein: 0, carbs: 27.0, fat: 0, fiber: 0, verified: true },
  { id: 'bv-21', name: 'Monster Ultra (Sugar-Free Energy Drink)', category: 'Beverages', servingUnit: '1 can (355ml)', servingGrams: 355, calories: 10, protein: 0, carbs: 2.0, fat: 0, fiber: 0, verified: true },
  { id: 'bv-22', name: 'Jaljeera (Cumin & Mint Digestive Drink)', category: 'Beverages', servingUnit: '1 glass (250ml)', servingGrams: 250, calories: 35, protein: 0.5, carbs: 8.0, fat: 0.1, fiber: 0.5, verified: true },
  { id: 'bv-23', name: 'Turmeric Golden Milk (Haldi Doodh with Ghee & Honey)', category: 'Beverages', servingUnit: '1 mug (250ml)', servingGrams: 250, calories: 175, protein: 7.5, carbs: 16.0, fat: 9.0, fiber: 0.5, verified: true },
  { id: 'bv-24', name: 'Beetroot & Carrot Detox Juice', category: 'Beverages', servingUnit: '1 glass (250ml)', servingGrams: 250, calories: 85, protein: 2.0, carbs: 19.0, fat: 0.3, fiber: 2.0, verified: true },
  { id: 'bv-25', name: 'Electral ORS / Electrolyte Solution', category: 'Beverages', servingUnit: '1 glass (250ml)', servingGrams: 250, calories: 50, protein: 0, carbs: 12.5, fat: 0, fiber: 0, verified: true },

  // ==========================================
  // 13. PACKAGED FOODS (25 items)
  // ==========================================
  { id: 'pk-1', name: 'Rolled Oats (Quaker / Kellogg\'s Unsweetened)', category: 'Packaged Foods', servingUnit: '1 scoop (40g)', servingGrams: 40, calories: 155, protein: 5.5, carbs: 27.0, fat: 2.8, fiber: 4.2, verified: true },
  { id: 'pk-2', name: 'Instant Masala Oats (Saffola)', category: 'Packaged Foods', servingUnit: '1 pouch (38g)', servingGrams: 38, calories: 145, protein: 3.5, carbs: 25.0, fat: 3.5, fiber: 3.2, verified: true },
  { id: 'pk-3', name: 'Corn Flakes (Kellogg\'s Original)', category: 'Packaged Foods', servingUnit: '1 cup (30g)', servingGrams: 30, calories: 115, protein: 2.1, carbs: 26.0, fat: 0.3, fiber: 0.9, verified: true },
  { id: 'pk-4', name: 'Muesli (Fruit & Nut with Almonds)', category: 'Packaged Foods', servingUnit: '1 bowl (45g)', servingGrams: 45, calories: 180, protein: 4.8, carbs: 32.0, fat: 3.8, fiber: 3.6, verified: true },
  { id: 'pk-5', name: 'Dark Chocolate (Amul 75% Dark)', category: 'Packaged Foods', servingUnit: '4 squares (25g)', servingGrams: 25, calories: 140, protein: 2.2, carbs: 11.0, fat: 9.8, fiber: 2.8, verified: true },
  { id: 'pk-6', name: 'Almonds (California Raw)', category: 'Packaged Foods', servingUnit: '1 handful (25g)', servingGrams: 25, calories: 145, protein: 5.2, carbs: 5.3, fat: 12.5, fiber: 3.1, verified: true },
  { id: 'pk-7', name: 'Walnuts / Akhrot (Raw Halves)', category: 'Packaged Foods', servingUnit: '1 handful (25g)', servingGrams: 25, calories: 165, protein: 3.8, carbs: 3.5, fat: 16.5, fiber: 1.7, verified: true },
  { id: 'pk-8', name: 'Cashews / Kaju (Raw)', category: 'Packaged Foods', servingUnit: '1 handful (25g)', servingGrams: 25, calories: 140, protein: 4.5, carbs: 7.5, fat: 11.0, fiber: 0.8, verified: true },
  { id: 'pk-9', name: 'Pistachios / Pista (Roasted Salted)', category: 'Packaged Foods', servingUnit: '1 handful (25g in shell)', servingGrams: 25, calories: 140, protein: 5.0, carbs: 7.0, fat: 11.2, fiber: 2.5, verified: true },
  { id: 'pk-10', name: 'Peanut Chikki (Jaggery & Groundnuts)', category: 'Packaged Foods', servingUnit: '1 piece (30g)', servingGrams: 30, calories: 155, protein: 4.2, carbs: 18.0, fat: 7.8, fiber: 1.2, verified: true },
  { id: 'pk-11', name: 'Parle-G Glucose Biscuits', category: 'Packaged Foods', servingUnit: '5 biscuits (25g)', servingGrams: 25, calories: 115, protein: 1.8, carbs: 20.0, fat: 3.2, fiber: 0.5, verified: true },
  { id: 'pk-12', name: 'Marie Gold Biscuits', category: 'Packaged Foods', servingUnit: '4 biscuits (24g)', servingGrams: 24, calories: 105, protein: 1.9, carbs: 19.0, fat: 2.4, fiber: 0.6, verified: true },
  { id: 'pk-13', name: 'NutriChoice Digestive High Fiber Biscuits', category: 'Packaged Foods', servingUnit: '2 biscuits (25g)', servingGrams: 25, calories: 120, protein: 2.2, carbs: 17.5, fat: 4.8, fiber: 1.8, verified: true },
  { id: 'pk-14', name: 'Haldiram\'s Aloo Bhujia', category: 'Packaged Foods', servingUnit: '1 portion (30g)', servingGrams: 30, calories: 175, protein: 3.5, carbs: 13.5, fat: 12.0, fiber: 1.5, verified: true },
  { id: 'pk-15', name: 'Haldiram\'s Khatta Meetha Namkeen', category: 'Packaged Foods', servingUnit: '1 portion (30g)', servingGrams: 30, calories: 165, protein: 3.0, carbs: 17.0, fat: 9.5, fiber: 1.2, verified: true },
  { id: 'pk-16', name: 'Maggi 2-Minute Masala Noodles', category: 'Packaged Foods', servingUnit: '1 pack (70g)', servingGrams: 70, calories: 310, protein: 6.8, carbs: 43.5, fat: 12.2, fiber: 2.2, verified: true },
  { id: 'pk-17', name: 'Kissan Mixed Fruit Jam', category: 'Packaged Foods', servingUnit: '1 tbsp (20g)', servingGrams: 20, calories: 55, protein: 0.1, carbs: 14.0, fat: 0, fiber: 0.2, verified: true },
  { id: 'pk-18', name: 'Maggi Rich Tomato Ketchup', category: 'Packaged Foods', servingUnit: '1 tbsp (15g)', servingGrams: 15, calories: 20, protein: 0.2, carbs: 4.8, fat: 0, fiber: 0.1, verified: true },
  { id: 'pk-19', name: 'FunFoods Eggless Mayonnaise', category: 'Packaged Foods', servingUnit: '1 tbsp (15g)', servingGrams: 15, calories: 85, protein: 0.2, carbs: 1.8, fat: 8.8, fiber: 0, verified: true },
  { id: 'pk-20', name: 'Hummus (Classic Chickpea Tahini Dip)', category: 'Packaged Foods', servingUnit: '2 tbsp (40g)', servingGrams: 40, calories: 95, protein: 3.2, carbs: 7.0, fat: 6.2, fiber: 2.4, verified: true },
  { id: 'pk-21', name: 'Lay\'s India\'s Magic Masala Chips', category: 'Packaged Foods', servingUnit: '1 small pack (30g)', servingGrams: 30, calories: 165, protein: 2.1, carbs: 16.0, fat: 10.5, fiber: 1.1, verified: true },
  { id: 'pk-22', name: 'Kurkure Masala Munch', category: 'Packaged Foods', servingUnit: '1 pack (40g)', servingGrams: 40, calories: 225, protein: 2.5, carbs: 23.0, fat: 13.5, fiber: 1.0, verified: true },
  { id: 'pk-23', name: 'Granola Bar (Chocolate Chip / Honey Nut)', category: 'Packaged Foods', servingUnit: '1 bar (35g)', servingGrams: 35, calories: 150, protein: 3.0, carbs: 24.0, fat: 5.0, fiber: 2.5, verified: true },
  { id: 'pk-24', name: 'Unsweetened Cocoa Powder (Hershey\'s / Cadbury)', category: 'Packaged Foods', servingUnit: '1 tbsp (10g)', servingGrams: 10, calories: 25, protein: 2.0, carbs: 5.5, fat: 1.0, fiber: 3.0, verified: true },
  { id: 'pk-25', name: 'Nutella Hazelnut Spread', category: 'Packaged Foods', servingUnit: '1 tbsp (18g)', servingGrams: 18, calories: 100, protein: 1.1, carbs: 11.0, fat: 5.7, fiber: 0.6, verified: true },

  // ==========================================
  // 14. FAST FOOD (25 items)
  // ==========================================
  { id: 'ff-1', name: 'McDonald\'s McChicken Burger', category: 'Fast Food', servingUnit: '1 burger (150g)', servingGrams: 150, calories: 400, protein: 15.0, carbs: 42.0, fat: 19.0, fiber: 2.2, verified: true },
  { id: 'ff-2', name: 'McDonald\'s McAloo Tikki Burger', category: 'Fast Food', servingUnit: '1 burger (145g)', servingGrams: 145, calories: 340, protein: 8.0, carbs: 48.0, fat: 13.0, fiber: 3.0, verified: true },
  { id: 'ff-3', name: 'McDonald\'s French Fries (Medium)', category: 'Fast Food', servingUnit: '1 medium (115g)', servingGrams: 115, calories: 340, protein: 4.0, carbs: 44.0, fat: 16.0, fiber: 3.8, verified: true },
  { id: 'ff-4', name: 'Subway 6-inch Roasted Chicken Breast Sub', category: 'Fast Food', servingUnit: '6-inch sub (230g)', servingGrams: 230, calories: 320, protein: 26.0, carbs: 42.0, fat: 5.0, fiber: 5.0, verified: true },
  { id: 'ff-5', name: 'Subway 6-inch Paneer Tikka Sub', category: 'Fast Food', servingUnit: '6-inch sub (240g)', servingGrams: 240, calories: 390, protein: 18.0, carbs: 46.0, fat: 15.0, fiber: 5.2, verified: true },
  { id: 'ff-6', name: 'Subway 6-inch Veggie Delite Sub', category: 'Fast Food', servingUnit: '6-inch sub (170g)', servingGrams: 170, calories: 210, protein: 8.0, carbs: 39.0, fat: 2.5, fiber: 5.0, verified: true },
  { id: 'ff-7', name: 'Domino\'s Farmhouse Veg Pizza (1 Regular Slice)', category: 'Fast Food', servingUnit: '1 slice (90g)', servingGrams: 90, calories: 210, protein: 7.5, carbs: 28.0, fat: 7.8, fiber: 1.8, verified: true },
  { id: 'ff-8', name: 'Domino\'s Chicken Pepperoni / Barbeque Pizza (1 Slice)', category: 'Fast Food', servingUnit: '1 slice (90g)', servingGrams: 90, calories: 240, protein: 11.0, carbs: 26.0, fat: 10.5, fiber: 1.5, verified: true },
  { id: 'ff-9', name: 'Domino\'s Stuffed Garlic Bread', category: 'Fast Food', servingUnit: '2 pieces (80g)', servingGrams: 80, calories: 260, protein: 7.0, carbs: 32.0, fat: 12.0, fiber: 1.5, verified: true },
  { id: 'ff-10', name: 'Burger King Crispy Veg Burger', category: 'Fast Food', servingUnit: '1 burger (140g)', servingGrams: 140, calories: 330, protein: 7.0, carbs: 46.0, fat: 13.5, fiber: 2.8, verified: true },
  { id: 'ff-11', name: 'Burger King Whopper (Chicken)', category: 'Fast Food', servingUnit: '1 burger (260g)', servingGrams: 260, calories: 570, protein: 28.0, carbs: 54.0, fat: 28.0, fiber: 3.5, verified: true },
  { id: 'ff-12', name: 'Veg Momos Steamed (6 Pcs with Spicy Chutney)', category: 'Fast Food', servingUnit: '6 pieces (150g)', servingGrams: 150, calories: 190, protein: 5.5, carbs: 34.0, fat: 3.5, fiber: 2.5, verified: true },
  { id: 'ff-13', name: 'Fried Chicken Momos (6 Pcs)', category: 'Fast Food', servingUnit: '6 pieces (160g)', servingGrams: 160, calories: 340, protein: 16.0, carbs: 30.0, fat: 17.5, fiber: 1.5, verified: true },
  { id: 'ff-14', name: 'Chicken Shawarma Roll (with Mayo & Rumali)', category: 'Fast Food', servingUnit: '1 roll (220g)', servingGrams: 220, calories: 440, protein: 26.0, carbs: 40.0, fat: 20.0, fiber: 2.5, verified: true },
  { id: 'ff-15', name: 'Veg Spring Rolls (2 pieces Fried)', category: 'Fast Food', servingUnit: '2 rolls (120g)', servingGrams: 120, calories: 250, protein: 4.5, carbs: 30.0, fat: 12.5, fiber: 2.2, verified: true },
  { id: 'ff-16', name: 'Veg Manchurian Gravy (Indo-Chinese)', category: 'Fast Food', servingUnit: '1 bowl (200g)', servingGrams: 200, calories: 260, protein: 5.0, carbs: 28.0, fat: 14.5, fiber: 3.0, verified: true },
  { id: 'ff-17', name: 'Chilli Paneer Dry (Indo-Chinese)', category: 'Fast Food', servingUnit: '1 plate (180g)', servingGrams: 180, calories: 360, protein: 18.0, carbs: 18.0, fat: 24.5, fiber: 2.2, verified: true },
  { id: 'ff-18', name: 'Veg Hakka Noodles', category: 'Fast Food', servingUnit: '1 plate (200g)', servingGrams: 200, calories: 320, protein: 6.5, carbs: 54.0, fat: 9.0, fiber: 3.5, verified: true },
  { id: 'ff-19', name: 'Chicken Hakka Noodles', category: 'Fast Food', servingUnit: '1 plate (240g)', servingGrams: 240, calories: 410, protein: 22.0, carbs: 52.0, fat: 13.5, fiber: 3.0, verified: true },
  { id: 'ff-20', name: 'Vada Pav (Mumbai Street Burger with Chutney)', category: 'Fast Food', servingUnit: '1 piece (120g)', servingGrams: 120, calories: 290, protein: 5.8, carbs: 42.0, fat: 11.2, fiber: 2.8, verified: true },
  { id: 'ff-21', name: 'Chole Bhature (1 Bhatura + Chole Bowl)', category: 'Fast Food', servingUnit: '1 combo plate (320g)', servingGrams: 320, calories: 560, protein: 16.0, carbs: 70.0, fat: 24.0, fiber: 8.5, verified: true },
  { id: 'ff-22', name: 'Pav Bhaji with Butter Pav (2 Pavs + Bhaji)', category: 'Fast Food', servingUnit: '1 plate (300g)', servingGrams: 300, calories: 460, protein: 9.5, carbs: 62.0, fat: 19.5, fiber: 6.5, verified: true },
  { id: 'ff-23', name: 'Taco Bell Crunchy Taco (Beans & Cheese)', category: 'Fast Food', servingUnit: '1 taco (90g)', servingGrams: 90, calories: 170, protein: 6.0, carbs: 18.0, fat: 8.5, fiber: 3.5, verified: true },
  { id: 'ff-24', name: 'KFC Popcorn Chicken (Medium)', category: 'Fast Food', servingUnit: '1 box (100g)', servingGrams: 100, calories: 310, protein: 17.0, carbs: 19.0, fat: 19.0, fiber: 1.0, verified: true },
  { id: 'ff-25', name: 'Chicken Cheese Quesadilla', category: 'Fast Food', servingUnit: '1 slice/half (150g)', servingGrams: 150, calories: 380, protein: 24.0, carbs: 28.0, fat: 20.0, fiber: 2.0, verified: true }
];
